export const AUTOMATION_SCHEMA_VERSION = 1 as const;

export type AutomationWorkflowDefinition = {
  id: "ava.system-report" | "ava.operations-brief";
  version: 1;
  displayName: string;
  artifactSlug: string;
  artifactSummary: string;
  trigger: "manual";
  risk: "read_only";
};

export const SYSTEM_REPORT_WORKFLOW = {
  id: "ava.system-report",
  version: 1,
  displayName: "AVA system health report",
  artifactSlug: "system-report",
  artifactSummary: "Verified AVA system health report generated by the pinned automation workflow.",
  trigger: "manual",
  risk: "read_only",
} as const satisfies AutomationWorkflowDefinition;

export const OPERATIONS_BRIEF_WORKFLOW = {
  id: "ava.operations-brief",
  version: 1,
  displayName: "AVA operations brief",
  artifactSlug: "operations-brief",
  artifactSummary: "Verified AVA operations brief generated by the pinned automation workflow.",
  trigger: "manual",
  risk: "read_only",
} as const satisfies AutomationWorkflowDefinition;

export const AUTOMATION_WORKFLOWS = [SYSTEM_REPORT_WORKFLOW, OPERATIONS_BRIEF_WORKFLOW] as const;
export type AutomationWorkflowId = (typeof AUTOMATION_WORKFLOWS)[number]["id"];

export function automationWorkflow(id: string): AutomationWorkflowDefinition | null {
  return AUTOMATION_WORKFLOWS.find((candidate) => candidate.id === id) ?? null;
}

export type AutomationRunStatus =
  | "queued"
  | "running"
  | "completed"
  | "failed"
  | "cancelled"
  | "timed_out"
  | "unavailable";

export type AutomationWorkflowHealth = {
  workflow: AutomationWorkflowDefinition;
  configured: boolean;
  available: boolean;
  reason: string;
  runtimeEvidence: "configured_endpoint" | "missing_configuration" | "deterministic_fixture";
};

export type AutomationProviderHealth = {
  schemaVersion: 1;
  provider: "activepieces";
  configured: boolean;
  available: boolean;
  executionMode: "sync_webhook" | "unavailable";
  reason: string;
  workflows: AutomationWorkflowHealth[];
  timeoutMs: number;
  runtimeEvidence: "configured_endpoint" | "missing_configuration" | "deterministic_fixture";
  usage: "not_reported";
  cost: "not_reported";
};

export type AutomationSystemSnapshot = {
  generatedAt: number;
  generatedAtIso: string;
  ready: boolean;
  provider: string | null;
  core: {
    brainReady: boolean;
    voiceReady: boolean;
    browserReady: boolean;
    memoryReady: boolean;
  };
  counts: {
    preferences: number;
    observations: number;
    projects: number;
    people: number;
    playbooks: number;
    watches: number;
  };
  integrations: {
    instagram: boolean;
    whatsapp: boolean;
    shopify: boolean;
    googlePlaces: boolean;
    screenVision: boolean;
    push: boolean;
    microsoftUfoAvailable: boolean;
  };
};

export type AutomationOperationsSnapshot = {
  generatedAt: number;
  generatedAtIso: string;
  windowHours: 24;
  readiness: {
    ready: boolean;
    provider: string | null;
    brainReady: boolean;
    voiceReady: boolean;
    browserReady: boolean;
    memoryReady: boolean;
  };
  recentRuns: {
    total: number;
    active: number;
    completed: number;
    failed: number;
    cancelled: number;
    timedOut: number;
    verified: number;
    notVerified: number;
  };
  attention: {
    pendingApprovals: number;
    blockedSelfImprovements: number;
    blockedWatcherSuccessors: number;
  };
  work: {
    pinnedNotes: number;
    notesDoing: number;
    notesInReview: number;
    activeSelfImprovements: number;
    shippedSelfImprovements: number;
    enabledWatches: number;
  };
  knowledge: {
    activeMemoryEntries: number;
    verifiedMemorySources: number;
  };
};

export type AutomationWorkflowSnapshot = AutomationSystemSnapshot | AutomationOperationsSnapshot;

export type AutomationExecutorStep = {
  id: string;
  status: "completed" | "failed" | "skipped";
  summary: string;
  durationMs: number | null;
};

export type AutomationExecutorResult = {
  schemaVersion: 1;
  workflowId: string;
  workflowVersion: number;
  requestKey: string;
  externalRunId: string | null;
  providerVersion: string | null;
  status: "succeeded" | "failed";
  steps: AutomationExecutorStep[];
  report: {
    title: string;
    markdown: string;
  } | null;
  error: {
    code: string;
    message: string;
  } | null;
  usage: "not_reported";
  cost: "not_reported";
};

export type AutomationExecutor = {
  readonly id: "activepieces" | "deterministic_fixture";
  health(): AutomationProviderHealth;
  workflowHealth(workflow: AutomationWorkflowDefinition): AutomationWorkflowHealth;
  execute(input: {
    requestKey: string;
    workflowId: AutomationWorkflowId;
    workflowVersion: number;
    snapshot: AutomationWorkflowSnapshot;
    signal: AbortSignal;
  }): Promise<AutomationExecutorResult>;
};

export type AutomationRun = {
  id: string;
  requestKey: string;
  workflowId: string;
  workflowVersion: number;
  executor: string;
  externalRunId: string | null;
  observabilityRunId: string;
  status: AutomationRunStatus;
  version: number;
  stepCount: number;
  inputSummary: unknown;
  outputSummary: unknown;
  artifactPath: string | null;
  artifactHash: string | null;
  memoryEntryId: string | null;
  verificationState: "unverified" | "verified" | "contradicted" | "unavailable";
  verificationMethod: string | null;
  errorCode: string | null;
  errorMessage: string | null;
  createdAt: number;
  updatedAt: number;
  completedAt: number | null;
};
